title: Sicong Zhao
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: >
  Data Scientist 
  <br><br>
  Designer 
  <br><br>
  <a href="https://www.linkedin.com/in/sicongzhao/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
